/*
Copyright (c) 2008 by AOL LLC
All rights reserved.
 
Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:
 
    * Redistributions of source code must retain the above copyright notice, this list of conditions
      and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions
      and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of AOL LLC nor the names of its contributors may be used to endorse or 
      promote products derived from this software without specific prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR 
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND 
FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR 
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER 
IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

({
	//New strings.
	"needAuth": "You need to sign in to AIM. Press the button below to go to the AIM service to sign in.",
	"Menu_SignOutAIMClearAuth": "Sign out & clear cookies",
	"Menu_ChangeExpressions": "Change Expressions",
	"BuddyInfo_Link_Text": "Buddy Info",

	//Existing strings.
	"AIM_ScreenName": "Screen Name",
	"AbbFriday": "F",
	"AbbMonday": "M",
	"AbbSaturday": "S",
	"AbbSunday": "S",
	"AbbThursday": "T",
	"AbbTuesday": "T",
	"AbbWednesday": "W",
	"Add": "Add",
	"AddBuddy_Label_NoScreenName": "Please enter a screen name.",
	"AddBuddy_Title": "Add Buddy",
	"AddGroup_Label_DuplicateGroupName": "Group %{0} already exists in Buddy List.",
	"AddGroup_Label_GroupNameTooLong": "The group name is too long, please make it shorter.",
	"Apr": "Apr",
	"April": "April",
	"AttachFile": "Attach File",
	"Aug": "Aug",
	"August": "August",
	"BackgroundColor": "Select text background color",
	"Basic_SwitchToRichEditor": "Switch to rich text editor",
	"Bold ": "Bold",
	"BuddyInfo_Label_IdleTime": "Idle Time:",
	"BuddyInfo_Label_OnlineTime": "Online Time:",
	"BuddyList_Label_Find": "Find in Buddy List",
	"BuddyList_Label_GroupOffline": "Offline",
	"BuddyList_Label_GroupRecentBuddies": "Recent Buddies",
	"BuddyStatus_Label_Available": "Available",
	"BuddyStatus_Label_BeRightBack": "Be Right Back",
	"BuddyStatus_Label_Blocked": "Blocked",
	"BuddyStatus_Label_CustomMessage": "Custom Away Message",
	"BuddyStatus_Label_CustomStatus": "Custom Status Message",
	"BuddyStatus_Label_IAmAway": "I Am Away",
	"BuddyStatus_Label_Idle": "Idle",
	"BuddyStatus_Label_Invisible": "Invisible (Appear Offline)",
	"BuddyStatus_Label_Mobile": "Mobile",
	"BuddyStatus_Label_Offline": "Offline",
	"BuddyStatus_Label_OnThePhone": "On The Phone",
	"BulletedList": "Bulleted List",
	"Button_Label_Send": "Send",
	"Cancel": "Cancel",
	"ChatError_AddBuddy": "Buddy name could not be added.  Maybe it's spelled wrong?",
	"ChatError_RemoveBuddy": "Buddy name could not be removed.",
	"ChatError_RemoveGroup": "The group could not be removed.",
	"ChatError_RenameGroup": "The group could not be renamed.",
	"ChooseFileTooltip": "Choose files to attach",
	"DateRFC2445": "yyyyMMdd",
	"DateRFC2445WithTime": "yyyyMMddHHmmss",
	"DateThisYear": "M/d",
	"DateToday": "H:mm",
	"DateWeek": "M/d, E",
	"DateYear": "yyyy/M/d",
	"Date_am": "am",
	"Date_pm": "pm",
	"DaysAbbrev": "d",
	"Dec": "Dec",
	"December": "December",
	"DecreaseIndent": "Decrease Indent",
	"Delete": "Delete",
	"DeleteBuddy_Label": "Are you sure you want to delete %{0}?",
	"DeleteGroup_Label": "Are you sure you want to delete Group %{0}?",
	"ErrorIMServer": "An error occurred while talking with the Instant Messaging Server.",
	"Error_ActionTimedOut": "Timeout for action: ",
	"Error_AimGeneric": "Your connection to the AIM system has been lost. Please try signing in again.",
	"Error_BadGetTokenResponse": "Bad getToken response: ",
	"Error_BadStartSessionResponse": "Bad startSession response: ",
	"Error_InvalidAuthState": "Invalid auth state: ",
	"Error_RateLimited": "Your connection to AIM has been dropped because you have done too much, too fast. Please wait awhile before signing in again.",
	"Feb": "Feb",
	"February": "February",
	"FirstDayOfWeek": "0",
	"Folder_SavedIMs": "IMs",
	"FontSize ": "Select font size",
	"FontType": "Select font type",
	"Fri": "Fri",
	"Friday": "Friday",
	"HorizontalRule": "Horizontal line",
	"HoursAbbrev": "h",
	"IMMenu_ClearWindow": "Clear Window",
	"IMMenu_ShowTimestamp": "Show timestamps",
	"IMSave_Empty": "Cannot save an empty conversation",
	"IMSave_Title": "IM conversation on %{0}",
	"IMSave_subject_prefix": "IM ({0} msgs) ",
	"IM_Group_Buddycount": "{0} Buddies",
	"IM_Label_AutoResponsePrefix": "Auto Response from ",
	"IM_Label_CloseConfirmation": "Close all {0} IMs?",
	"IM_Label_NoRecipient": "Please enter a recipient for the IM.",
	"IM_Notice_AIM": "Messages will be sent to AIM.",
	"IM_Notice_Blocked": "You will not receive IMs from:",
	"IM_Notice_BuddyAdded": "Your buddy was added.",
	"IM_Notice_BuddyDeleted": "Your buddy was deleted.",
	"IM_Notice_ErrorCode": "Error Code: %{0}",
	"IM_Notice_GroupDeleted": "Your group was deleted.",
	"IM_Notice_GroupRenamed": "Your group was updated.",
	"IM_Notice_Ignored": "IMs from %{0} will be ignored for this session.",
	"IM_Notice_InvalidTarget": "Invalid Target.",
	"IM_Notice_MessageNotSent": "Your message was not sent to %{0}.",
	"IM_Notice_MessageTooLarge": "Your message is too large. Please shorten it and try again.",
	"IM_Notice_OfflineIM": "[Offline IM sent %{0}]",
	"IM_Notice_OfflineLinks": "Send: %{0}",
	"IM_Notice_PhoneNumber": "Enter Phone Number",
	"IM_Notice_PresenceTitle": "Click for Menu",
	"IM_Notice_RemoteUserAway": "%{0} is away.",
	"IM_Notice_RemoteUserBlocked": "%{0} is blocked by you, and cannot receive your IM.",
	"IM_Notice_RemoteUserOffline": "%{0} is offline.",
	"IM_Notice_RemoteUserOfflineMaybe": "%{0} is offline and may receive your IMs when signing back in.",
	"IM_Notice_RemoteUserOnline": "%{0} is online.",
	"IM_Notice_SMS": "Messages will be sent to mobile phone.",
	"IM_Notice_SMSDisclaimer": "Charges may apply to recipient.",
	"IM_Notice_SMSInfo": "Click for more information.",
	"IM_Notice_SMS_size": "Characters left: %{0}",
	"IM_Notice_Saving": "Saving conversation...",
	"IM_Notice_UnblockLink": "Unblock",
	"IM_Notice_Unblocked": "You may now receive IMs from %{0}.",
	"IM_Notice_UserBlocked": "%{0} has blocked you, and will not receive your IM.",
	"IM_Notice_UserTyped": "%{0} has entered text",
	"IM_Notice_UserTyping": "%{0} is typing a message",
	"IM_Title": "IM - {0}",
	"IM_Title_MultipleIMs": "{0} IM's",
	"IM_Title_NewCount": " ({0} New)",
	"IM_Title_NewIM": "New IM",
	"IM_Title_NewText": "New Text",
	"IM_Title_OneIM": "1 IM",
	"IM_Title_Text": "Text - {0}",
	"IMshort": "IM",
	"IncreaseIndent": "Increase Indent",
	"InsertSmiley": "Select Smiley",
	"Italic ": "Italicize",
	"Jan": "Jan",
	"January": "January",
	"Jul": "Jul",
	"July": "July",
	"Jun": "Jun",
	"June": "June",
	"JustifyCenter": "Justify Center",
	"JustifyLeft": "Justify Left",
	"JustifyRight": "Justify Right",
	"KnockKnock_Label_Accept": "Accept",
	"KnockKnock_Label_Block": "Block",
	"KnockKnock_Label_Decline": "Decline",
	"KnockKnock_Label_Prompt": "{0} wants to chat with you. What do you want to do?",
	"KnockKnock_Label_Unblock": "Unblock",
	"Label_GroupEdit": "Edit",
	"Mar": "Mar",
	"March": "March",
	"May": "May",
	"Menu_AddGroup": "Add Group",
	"Menu_Block": "Block",
	"Menu_Ignore": "Ignore",
	"Menu_SignOutAIM": "Sign out of AIM",
	"Message_Label_UnsupportedBrowser": "The AIM Panel is not supported by your current browser or operating system.",
	"MinutesAbbrev": "m",
	"Mon": "Mon",
	"Monday": "Monday",
	"NewFolder": "New Folder",
	"No": "No",
	"NoAIMAccount": "does not have an AIM account.",
	"NoMatchesFound": "No matches were found.",
	"Notice_NearRateLimit": "You are about to be rate limited. Please wait a few seconds before sending, to avoid being rate-limited.",
	"Nov": "Nov",
	"November": "November",
	"OK": "OK",
	"Oct": "Oct",
	"October": "October",
	"OrderedList": "Numbered List",
	"SMSLegalInfoURL": "",
	"Sat": "Sat",
	"Saturday": "Saturday",
	"Save": "Save",
	"ScreenName": "Screen Name",
	"SecondsAbbrev": "s",
	"SendEmail": "Email",
	"Sep": "Sep",
	"September": "September",
	"Settings_Label_AutoSignOn": "Automatically start AIM next time", //modified
	"ShortMay": "May",
	"SignIn": "Sign In",
	"SignInAIMToSendIM": "Sign in to AIM panel to send an IM",
	"SignInAIMToSendIMToBuddy": "Sign in to AIM panel to send an IM to:",
	"SignInAIMToSendText": "Sign in to AIM panel to send a text message",
	"SignInAIMToSendTextToBuddy": "Sign in to AIM panel to send a text message to:",
	"SignOnStatus_Connecting": "Connecting...",
	"SignOnStatus_Offline": "Start chatting with friends and family now!",
	"SignOnStatus_Offline_SignInForIm": "Sign in to AIM to send a message",
	"Sun": "Sun",
	"Sunday": "Sunday",
	"Text_Message": "Text",
	"Thu": "Thu",
	"Thursday": "Thursday",
	"TimeAgo_NDays": "{0} days ago",
	"TimeAgo_NHours": "{0} hrs ago",
	"TimeAgo_NMinutes": "{0} min ago",
	"TimeAgo_NSeconds": "{0} sec ago",
	"TimeAgo_OneDay": "yesterday",
	"TimeAgo_OneHour": "1 hr ago",
	"TimeAgo_OneMinute": "1 min ago",
	"TimeAgo_PreviousYearDate": "$(DateStrings/DateYear)",
	"TimeAgo_ThisYearDate": "$(DateStrings/DateThisYear)",
	"To": "To",
	"Today": "Today",
	"Tue": "Tue",
	"Tuesday": "Tuesday",
	"Underline": "Underline",
	"UnspecifiedError": "An unspecified server error occurred. Please try again later.",
	"ViewHTMLSource": "View HTML Source",
	"Wed": "Wed",
	"Wednesday": "Wednesday",
	"Yes": "Yes",
	"Yesterday": "Yesterday"
})
